### ISSUE TITLE
Dataset Release

### ISSUE THREAD

**Issue by 34j** [pkhungurn/talking-head-anime-4#2]
@pkhungurn Hello. Thanks for publishing this great project. I assume that you live in Japan, and according to our country's copyright law, datasets for information analysis purposes could be legally released, given that the MMD models you used are already available to the public for free. The manually annotated MMD models and the images generated by them that you have been using since tha3 should have a wide range of applications (especially the former), and I would definitely appreciate it if you could release them for the development of of this field. (If this is not possible, would you mind giving me the dataset privately?) Thank you very much in advance.

**Comment by pkhungurn** [comment]
Sorry. The dataset will not be released.
